name: ci

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test-on-ci:
    # 指定可能なもの一覧 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # イメージ詳細 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    # イメージにNode.js, yarn, docker, docker-compose, aws cliはあらかじめインストールされている
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: dumy
      AWS_SECRET_ACCESS_KEY: dumy
      AWS_DEFAULT_REGION: local-env
      STRIPE_KEY_SECRET: ${{ secrets.STRIPE_KEY_SECRET_TEST_MODE }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: run test
        run: yarn test
